<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Document</title>
        <script>
            // finally는 try에서 성공/실패 상관없이 항상 동작이 됨
            // 그래서 반드시 마무리 지어야하는 코드는 finally구문에 작성하면 된다.

            // 예외가 발생하지 않은 상황
            try {
                const result = 10 + 20;
                console.log(result);
            } catch (exception) {
                console.log("catch에서 예의 얻음");
            } finally {
                console.log("1번째 finally");
            }

            // 예외가 발생하는 상황
            try {
                willExcept.happy();
                console.log("2번째코드 수행 완료~");
            } catch (exception) {
                console.log("2번째 catch에서 예의 얻음");
            } finally {
                console.log("2번째 finally");
            }
        </script>
    </head>
    <body></body>
</html>
